# frozen_string_literal: true

module Imagusu
  module DesignSystem
    class RadioGroupComponent < Internal::FormControlComponent
      HTML_ATTRIBUTES = %i[data form].freeze
      def initialize(options:, selected: Internal::FormControlComponent::UNSET, include_hidden: true, disabled_values: [], **attributes)
        super(**attributes)
        @options = normalize_options(options)
        @selected = selected
        @include_hidden = include_hidden
        @disabled_values = Array(disabled_values)

        validate_boolean!(:include_hidden, @include_hidden)
        validate_html_attributes!(HTML_ATTRIBUTES)
        validate_unique_values!
      end

      private

      def fieldset_attributes
        attributes = control_attributes(css_class: "ids-radio-group", allowed: HTML_ATTRIBUTES).except(:required)
        data = attributes.fetch(:data, {})
        raise ArgumentError, "data must be a Hash" unless data.is_a?(Hash)

        attributes.merge(data: data.merge(state: state_tokens))
      end

      def radio_buttons
        options = {include_hidden: rails_hidden_field?, disabled: @disabled_values}
        options[:checked] = @selected unless @selected.equal?(Internal::FormControlComponent::UNSET)
        html_options = {
          required: @required,
          disabled: @disabled,
          class: "ids-radio-group__control",
          form: external_form_id
        }.compact

        controls = form.collection_radio_buttons(method, @options, :last, :first, options, html_options) do |builder|
          tag.div(class: "ids-radio-group__option") do
            safe_join([
              builder.radio_button,
              builder.label(class: "ids-radio-group__label")
            ])
          end
        end

        safe_join([external_hidden_field, controls].compact)
      end

      def rails_hidden_field?
        @include_hidden && !@disabled && external_form_id.nil?
      end

      def external_hidden_field
        return unless @include_hidden && !@disabled && external_form_id

        form.hidden_field(
          method,
          value: "",
          id: nil,
          form: external_form_id,
          autocomplete: "off"
        )
      end

      def external_form_id
        @html_attributes[:form]
      end

      def normalize_options(options)
        raise ArgumentError, "options must be a non-empty Array" unless options.is_a?(Array) && options.any?

        options.map do |option|
          unless option.is_a?(Array) && option.length == 2
            raise ArgumentError, "each option must contain label and value"
          end

          option_label, value = option
          raise ArgumentError, "radio option labels must not be empty" if option_label.to_s.strip.empty?
          raise ArgumentError, "radio option values must not be empty" if value.to_s.empty?

          [option_label, value]
        end
      end

      def validate_unique_values!
        ids = @options.map { |_, value| "#{id}_#{sanitized_radio_value(value)}" }
        return if ids.uniq.length == ids.length

        raise ArgumentError, "radio option values must produce unique HTML IDs"
      end

      # Matches the value suffix generated by Rails collection radio helpers.
      def sanitized_radio_value(value)
        value.to_s.gsub(/[\s.]/, "_").gsub(/[^-[[:word:]]]/, "").downcase
      end
    end
  end
end
